language: node_js
node_js:
- stable
cache: yarn
script:
- yarn
- yarn build
- yarn test:single
notifications:
  slack:
    secure: cjzSm4fk8bleGu2oaCkUnAGWluBwfoOsdtBY6uxSw2+iOrmsS/mUDb2wGuOSZe2L/yROJTjsYM3fYvJFuqPFDFR8uj2EUWGapHIX86j3zrdlG0P7Reja0cgzohmHkZrjQcju/Ql3iz6MT/2+Pwtxgu6cRVRCpQuJoq1+D0Q5h/QSeQIDj8JH/rupDucWInmWxl6gDRJeQ1M3TdQ2A+jtbD43r8XCkvvbQHTh92PFIIW+mrD0GRNxQ43A3ihJ9zyuvC6ibDNX6yBTQcYmsgordgiRxrr3bg5gmwZYNZ2C/FXI3P968BkpG+ZQBh2i860sMlLv8FXCk0wfO/i6gyMOAi1GeRyQJcABUWoVUKXWpKBHl6wQIjhOrDLA7YfE+2nHuef1ZmJ0XS45kJ9blsYdz288M1iuLrt8w8mEybyr6pNmsNw8+OVxyyfAAJIbRhzEE/BoUB7y6x9hzabCCW/SHm8jrWbJU8dOzHuJB0TT0bUjhk4fJkzBT+6YURJb3bfmgT1vZ1Td9VJS3+muHXpKtatsnCXRZSm8Jl84LxrTMDQKfTJ9lcef9qEL4xdD+WJhipo8oRCow4KZ8hg+iC47xDY+m2bUlzzJ0F03oe2lekZhLOgnWG/+XZ0aSYIN7zJ9xfyIrXTo/wpn4SUjQxGu6yFOOmHQmX9ymRUodBGXCSY=
