language: node_js
node_js:
- stable
cache: yarn
script:
- yarn
- yarn build
- yarn test:single
notifications:
  slack:
    secure: Q3m9kaPTeKkli8i2pD2HKHa9k0992s/f/MHYvMm07vjbuWCfQY0YtYQicyPHC9e1AemkQCf3vEKl7T9TlOdsifSS8nIEFqgvoBQKmjq74/95LNQuzNE31g8Xl33H2WVvTA1Go7HkOa4sZ1bxqcaxGte7rLm6XVmLrBDzExi6bx+xSNWwIhxI0lf2r1lXT8OvnHduEdKKR/JM7FnAEWXhBzDg6gYpXbvRp8IUgtpW+Xe4y38OblugIel0lFOSLHu7qtwGVgxjLyxxwH4/wlwIMwPqOR8S4qt8O8U+b6bg1JYOYr6TzjtGMq7us4F/f9KwqOBc8yXdeckX8iamTVE5b/Dj+nrNtlHNZYB1TQa3JylpyO6CE5QWKP7j2guzghbEZrkI79iNi9C6jr+S3XmbdEOL4iENkQi5VXR6foMgiUl0MsWb3IsQl23eZ4+a7trCauPo5qEoTX+tWhUb47wPaXQV1KDBV20LbX3DT1E0RVoouXR2kkcc8Mgyh9n1SvglDQGcIGAaynxGyRkERzhfUbL4t6iaKXw5twG5FAJ9QU14xq869HA4kE8LRMU0ApHG+YsAx1HwA72z8urGsC1+qEIw6DMegPoY+I74coL/A0zpg8txBT5kKQaGgf0KR4ot3WrkPcvR0jGsMio7IklPAHgCCoChj6E2FbPn0Q5EqC0=
