language: node_js
node_js:
  - stable
cache: yarn
script:
  - yarn
  - yarn build
  - yarn test:single
notifications:
  slack:
    secure: Pg3/jvUqxk8D5mOJcFB6jqFpDArm2i3WYL7rjobeuoDmxpvO4gigteVpWBgeQDoteUtiaaqfz8mr5HHMJ7Lfp9zCkd4hHgzXjHgzkibGABw7k3fxz5v3Q0AOC52/hOIvJWqtW1ekxHCqQq654TII7vBwgrnpRuNztAIN+CZM7Tso+5HpdHGxP2xXsRVFSS4NInz8QEtq6GsTK9VMOHolhoYyyAzrjyLMNbsan0d70gj5+y2nQReSLGa55j+rEk4IVTMJBJ1+VaF7f2h3QzWnoSK5i8cRPSb0MoeY+0mg4jaEQOZA3Ur9eIrM2SoNOuk8/PRcZdNQWC3DIwtPP+A4BIh8qUbvUXrWxXGb3bd8fsyUdQGD2QfqOrToq6Qt1PLh3TrnF3sZhOVEfm1DkCOkEi78G5gjFqBPUeLL7PTa30ba50SCcnTy6S+dk0s/ohvKSOhHzBZOQx9Q7ZVbELrG1Dy6/c6ESlBRBsOyltI3HSOdj9qimPjNj4HwOdz4gW1iKA5Wzx9i9ZWd5TF0dcWSbO0XniyNDYJLc1eSEUr87qogsj2GdF2ANB6TCTmMLHUhDl68m4HxnncZ+nReoeAfm20sEe2wU/AYgNN6U0x/Je4fwmttoABNu3Ng0X6FdBiZVbgeNe/JKCB+Ah840oLCiZp/yh2dpdyUiGwSlEU5yZ0=
